import {describe, expect, it} from 'vitest'
import {EXPECTED_CONTENT_USAGE, validateRobots} from '../../scripts/audit/validate-robots.mjs'
import {GET as getRobotsTxt} from '../../src/pages/robots.txt'
import REPOSITORY_GOLDEN from './golden/robots-ai-crawlers.json'

const GOLDEN = {aiTrainingBotsBlockedExceptLlmsTxt: ['GPTBot', 'ClaudeBot'], aiSearchAgentsAllowedFullSite: ['OAI-SearchBot']}

const SITEMAP_URL = 'https://jonathanlloyd.me/sitemap-index.xml'

interface RobotsBodyOverrides {
  sitemap?: string
  trainingAgents?: string[]
  searchAgents?: string[]
  additionalLines?: string[]
}

function robotsBody(overrides: RobotsBodyOverrides = {}) {
  const sitemap = overrides.sitemap ?? `Sitemap: ${SITEMAP_URL}`
  const trainingAgents = overrides.trainingAgents ?? GOLDEN.aiTrainingBotsBlockedExceptLlmsTxt
  const searchAgents = overrides.searchAgents ?? GOLDEN.aiSearchAgentsAllowedFullSite
  const additionalLines = overrides.additionalLines?.join('\n') ?? ''
  const trainingBlocks = trainingAgents.map((agent) => `User-agent: ${agent}\nAllow: /llms.txt\nDisallow: /`).join('\n\n')
  const searchBlocks = searchAgents.map((agent) => `User-agent: ${agent}\nAllow: /`).join('\n\n')

  return `User-agent: *\nAllow: /\n\n${additionalLines}\n\n${trainingBlocks}\n\n${searchBlocks}\n\n${sitemap}\n`
}

describe('validateRobots', () => {
  it('accepts the robots.txt generated by the repository endpoint', async () => {
    const body = await getRobotsTxt().text()
    expect(validateRobots(body, REPOSITORY_GOLDEN, EXPECTED_CONTENT_USAGE)).toEqual([])
  })

  it('accepts the intended directives, crawler policy, sitemap, and HTTP preference', () => {
    expect(validateRobots(robotsBody(), GOLDEN, EXPECTED_CONTENT_USAGE)).toEqual([])
  })

  it('fails a Sitemap directive pointing elsewhere', () => {
    const findings = validateRobots(robotsBody({sitemap: 'Sitemap: https://elsewhere.example/sitemap.xml'}), GOLDEN, EXPECTED_CONTENT_USAGE)
    expect(findings.map((finding) => finding.id)).toContain('robots-sitemap-directive')
  })

  it('fails a missing or changed Content-Usage response header', () => {
    const missing = validateRobots(robotsBody(), GOLDEN, null)
    const changed = validateRobots(robotsBody(), GOLDEN, 'train-ai=n, search=y, ai-input=y')

    expect(missing.map((finding) => finding.id)).toContain('content-usage-header')
    expect(changed.map((finding) => finding.id)).toContain('content-usage-header')
  })

  it.each([
    'Content-Signal: search=yes, ai-train=no, ai-input=yes',
    'Content-Usage: train-ai=n, search=y',
    'Future-Directive: value',
    'malformed line without a colon'
  ])('rejects a Lighthouse-unsafe robots.txt line: %s', (line) => {
    const findings = validateRobots(robotsBody({additionalLines: [line]}), GOLDEN, EXPECTED_CONTENT_USAGE)
    expect(findings).toContainEqual(expect.objectContaining({severity: 'fail', id: 'robots-unsupported-directive'}))
  })

  it('fails when a golden AI-crawler User-agent section is missing', () => {
    const findings = validateRobots(robotsBody({trainingAgents: ['ClaudeBot']}), GOLDEN, EXPECTED_CONTENT_USAGE)
    expect(findings).toContainEqual(expect.objectContaining({severity: 'fail', id: 'robots-ai-crawler-missing', message: expect.stringContaining('GPTBot')}))
  })

  it('fails when a training crawler can read the dashboard', () => {
    const body = robotsBody().replace('User-agent: GPTBot\nAllow: /llms.txt\nDisallow: /', 'User-agent: GPTBot\nAllow: /')
    const findings = validateRobots(body, GOLDEN, EXPECTED_CONTENT_USAGE)
    expect(findings).toContainEqual(expect.objectContaining({severity: 'fail', id: 'robots-ai-training-policy'}))
  })

  it('fails when a search crawler is blocked from the site', () => {
    const body = robotsBody().replace('User-agent: OAI-SearchBot\nAllow: /', 'User-agent: OAI-SearchBot\nDisallow: /')
    const findings = validateRobots(body, GOLDEN, EXPECTED_CONTENT_USAGE)
    expect(findings).toContainEqual(expect.objectContaining({severity: 'fail', id: 'robots-ai-search-policy'}))
  })

  it('warns, but does not fail, for a new not-yet-golden User-agent section', () => {
    const findings = validateRobots(robotsBody({searchAgents: ['OAI-SearchBot', 'SomeNewBot']}), GOLDEN, EXPECTED_CONTENT_USAGE)
    const newBotFinding = findings.find((finding) => finding.id === 'robots-ai-crawler-new')
    expect(newBotFinding?.severity).toBe('warn')
    expect(findings.some((finding) => finding.severity === 'fail')).toBe(false)
  })
})
